# Generated by Django 4.1.3 on 2023-03-05 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_customer_product_order_cart'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='Profile',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='customer',
            new_name='profile',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='locality',
            new_name='residence',
        ),
    ]
