# Generated by Django 4.1.3 on 2023-03-05 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_customer_profile_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='profile',
        ),
    ]
