# Generated by Django 4.1.3 on 2023-03-05 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_product_gender_alter_profile_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='carousel',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=3, null=True),
        ),
    ]
